# Playbook para rodar um comando no host remoto, com o powershell utilizando o modulo win_shell, e exibir o resultado na tela.

- name: Task para rodar nos hosts Windows
  hosts: windows
  tasks:

  - name: Roda um comando no powershell e exibe na tela o resultado
    win_shell: Get-Content C:\ansible_wu.txt
    register: shell

  - debug: var=shell.stdout_lines
