 - name: Playbook #Name of the playbook#
    hosts: linux #A set of hosts usually grouped together as a host group and defined in inventory file(hosts)#
    become: yes #To tell ansible this play has to be executed with elevated privileges#
    become_user: root #the user name that we want to switch to like compare it with sudo su - user#

    tasks:
      - name: ensure apache is at the latest version #Descriptio ond the task#
        yum: #Module Name#
          name: httpd #Arguments#
          state: latest #Arguments#

      - name: ensure apache is running
        service:
          name: httpd
          state: started
